### PR TITLE
Add empty host and leading slash to Windows file paths

### PR DESCRIPTION
**Pull request by phil-davis**
1) add an explicit unit test for issue #31 
2) Adjust README to mention Windows-style paths
3) Add empty host and leading slash to Windows file paths (this is a remake of PR #71
4) changelog and version bump to 3.0.0

### CODE REVIEW

**Comment by phil-davis** [comment]
Wait until we decide the final actions to resolve issue #81 because maybe the text here will only apply to the next major release.

**Comment by phil-davis** [comment]
I will finish this tomorrow - give people a few hours to point out any errors I might have made in the releases 2.2.4 and 2.3.2

**Comment by phil-davis** [comment]
A week has passed - let's get moving again!

**Comment by staabm** [comment]
all good - thanks for working on it phil!

**Pull request merged**
